services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:8080"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "3003:3002"
    networks:
      - app-network
    deploy:
      replicas: 2

networks:
  app-network:
    driver: bridge
